# Generated by Django 4.1.7 on 2023-03-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timg', models.ImageField(upload_to='pics')),
                ('Tname', models.CharField(max_length=250)),
                ('Tdesc', models.TextField()),
            ],
        ),
    ]
