# Generated by Django 4.1.7 on 2023-03-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='defaultt', upload_to='imgfolder'),
            preserve_default=False,
        ),
    ]
